// Generates build outputs from schemas/v1/ at the repository root, all ignored by
// git:
// - src/generated/messages.ts: a TypeScript type for every message schema, named
//   after its `t` (HelloMsg, ReadyMsg, ...), and the ClientMsg and ServerMsg unions;
// - src/generated/client-validators.ts and server-validators.ts: Ajv standalone
//   validators for every message type and both direction aggregates, with no
//   runtime dependency.
import {
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { URL, fileURLToPath } from "node:url";
import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";

const schemaDir = fileURLToPath(
  new URL("../../../schemas/v1/", import.meta.url),
);
const outDir = fileURLToPath(new URL("../src/generated/", import.meta.url));
const HEADER =
  "// Generated by scripts/generate.mjs from schemas/v1; do not edit.\n";

const read = (rel) => JSON.parse(readFileSync(schemaDir + rel, "utf8"));
const common = read("common.schema.json");
const byId = new Map([[common.$id, common]]);

// The message schemas of each direction, in the order of its aggregate, which must
// list every schema of the direction's directory.
const directions = ["client", "server"].map((dir) => {
  const aggregate = read(`${dir}.schema.json`);
  const files = readdirSync(schemaDir + dir).filter((f) =>
    f.endsWith(".schema.json"),
  );
  const ids = files
    .map((f) => read(`${dir}/${f}`))
    .map((s) => {
      byId.set(s.$id, s);
      return s.$id;
    });
  const listed = aggregate.oneOf.map((branch) => branch.$ref);
  if (listed.length !== ids.length || ids.some((id) => !listed.includes(id))) {
    throw new Error(`${dir}.schema.json must list every schema under ${dir}/`);
  }
  byId.set(aggregate.$id, aggregate);
  return { dir, aggregate, messages: listed.map((id) => byId.get(id)) };
});

// Type names: HelloMsg for `hello`; a `t` sent in both directions (ping, pong)
// takes its direction as a prefix (ClientPingMsg, ServerPingMsg).
const pascal = (s) =>
  s
    .split("_")
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");
const tOf = (schema) => schema.properties.t.const;
const allTs = directions.flatMap((d) => d.messages.map(tOf));
const typeName = (dir, schema) =>
  (allTs.filter((t) => t === tOf(schema)).length > 1 ? pascal(dir) : "") +
  `${pascal(tOf(schema))}Msg`;

// ---- JSON Schema to TypeScript, for the keywords the protocol schemas use. A
// keyword or combination outside these fails the build instead of yielding a
// wrong type.
const ANNOTATION = ["$schema", "$id", "$defs", "title", "description"];
const VALUE_ONLY = [
  "minimum",
  "maximum",
  "minLength",
  "maxLength",
  "minItems",
  "maxItems",
  "pattern",
];
const STRUCTURAL = [
  "$ref",
  "type",
  "properties",
  "required",
  "additionalProperties",
  "const",
  "enum",
  "oneOf",
  "allOf",
  "items",
];

function resolve(ref) {
  const [uri, pointer = ""] = ref.split("#");
  let node = byId.get(uri);
  for (const key of pointer.split("/").filter(Boolean)) node = node?.[key];
  if (!node) throw new Error(`unresolved $ref ${ref}`);
  return node;
}

const deref = (schema) => (schema.$ref ? resolve(schema.$ref) : schema);

function doc(text, indent) {
  return text ? `${indent}/** ${text.replaceAll("*/", "*\\/")} */\n` : "";
}

function ts(schema, indent) {
  const keys = Object.keys(schema);
  const unmapped = keys.filter(
    (k) => ![...ANNOTATION, ...VALUE_ONLY, ...STRUCTURAL].includes(k),
  );
  if (unmapped.length) throw new Error(`no TypeScript mapping for ${unmapped}`);
  const structural = keys.filter((k) => STRUCTURAL.includes(k));
  const only = (...allowed) => {
    if (structural.some((k) => !allowed.includes(k))) {
      throw new Error(`no TypeScript mapping for ${structural} together`);
    }
  };
  if ("$ref" in schema) {
    only("$ref");
    return ts(resolve(schema.$ref), indent);
  }
  if ("const" in schema || "enum" in schema) {
    only("const", "enum", "type");
    const values = "const" in schema ? [schema.const] : schema.enum;
    return values.map((v) => JSON.stringify(v)).join(" | ");
  }
  if ("oneOf" in schema) {
    only("oneOf");
    return schema.oneOf.map((s) => ts(s, indent)).join(" | ");
  }
  switch (schema.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array": {
      const item = ts(schema.items ?? {}, indent);
      return /^[\w"]+$/.test(item) ? `${item}[]` : `(${item})[]`;
    }
    case "object":
      return object(schema, indent);
    default:
      throw new Error(`no TypeScript mapping for type ${schema.type}`);
  }
}

// The properties a schema names are typed; fields it does not name, which
// receivers ignore on the wire, are not. An object that names none is a record.
function object(schema, indent) {
  const inner = `${indent}  `;
  const properties = Object.entries(schema.properties ?? {});
  const required = new Set(schema.required ?? []);
  for (const key of required) {
    if (!schema.properties?.[key])
      throw new Error(`required ${key} is untyped`);
  }
  const lines = properties.map(([key, sub]) => {
    if (!/^[A-Za-z_$][\w$]*$/.test(key)) throw new Error(`property ${key}`);
    const optional = required.has(key) ? "" : "?";
    return `${doc(deref(sub).description, inner)}${inner}${key}${optional}: ${ts(sub, inner)};`;
  });
  const extra = schema.additionalProperties;
  if (typeof extra === "object") {
    if (properties.length)
      throw new Error("additionalProperties with properties");
    lines.push(`${inner}[key: string]: ${ts(extra, inner)};`);
  } else if (!properties.length && extra !== false) {
    lines.push(`${inner}[key: string]: unknown;`);
  }
  const type = `{\n${lines.join("\n")}\n${indent}}`;
  return schema.allOf ? `${type} & ${conditionals(schema, indent)}` : type;
}

// allOf is mapped when it is a list of if/then pairs keyed on the const of one
// required property whose enum they cover (action: the params of each kind). It
// becomes a union discriminated by that property.
function conditionals(schema, indent) {
  const inner = `${indent}  `;
  const key = Object.keys(schema.allOf[0]?.if?.properties ?? {})[0];
  const values = schema.allOf.map((pair) => {
    const cond = pair.if?.properties ?? {};
    if (
      Object.keys(pair).sort().join() !== "if,then" ||
      Object.keys(pair.if).join() !== "properties" ||
      Object.keys(cond).join() !== key ||
      Object.keys(cond[key]).join() !== "const"
    ) {
      throw new Error("allOf is mapped only as if/then pairs on one const");
    }
    return cond[key].const;
  });
  const domain = deref(schema.properties?.[key] ?? {}).enum;
  if (
    !schema.required?.includes(key) ||
    !domain ||
    domain.some((v) => !values.includes(v))
  ) {
    throw new Error(`the if/then pairs must cover every value of ${key}`);
  }
  const branches = schema.allOf.map(({ then }, i) => {
    const named = Object.keys(then.properties ?? {});
    const branch = {
      ...then,
      type: "object",
      properties: { [key]: { const: values[i] }, ...then.properties },
      required: [key, ...named.filter((k) => schema.required.includes(k))],
    };
    return `${inner}| ${object(branch, inner)}`;
  });
  return `(\n${branches.join("\n")}\n${indent})`;
}

let types = HEADER;
for (const { dir, aggregate, messages } of directions) {
  for (const schema of messages) {
    const summary = [schema.title, schema.description].filter(Boolean);
    types += `\n${doc(summary.join(". "), "")}export type ${typeName(dir, schema)} = ${ts(schema, "")};\n`;
  }
  const summary = [aggregate.title, aggregate.description].filter(Boolean);
  const union = messages.map((s) => `\n  | ${typeName(dir, s)}`).join("");
  types += `\n${doc(summary.join(". "), "")}export type ${pascal(dir)}Msg =${union};\n`;
}

// ---- Standalone validators, one module per direction so that a bundler drops the
// validators of a direction an application does not use (the package has no side
// effects). Ajv's output requires its runtime ucs2length for minLength and
// maxLength; that require is replaced by the same count of code points, and the
// build fails if the output imports anything else.
const ajv = new Ajv2020({
  code: { source: true, esm: true, lines: true },
  strict: true,
});
ajv.addSchema(common);
for (const { aggregate, messages } of directions) {
  ajv.addSchema([aggregate, ...messages]);
}

function validators(dir, aggregate, messages) {
  const exported = new Map(
    [...messages, aggregate].map((schema) => {
      const type =
        schema === aggregate ? `${pascal(dir)}Msg` : typeName(dir, schema);
      return [`validate${type}`, { id: schema.$id, type }];
    }),
  );
  const refs = Object.fromEntries(
    [...exported].map(([name, { id }]) => [name, id]),
  );
  let code = standaloneCode(ajv, refs)
    .replace(/^"use strict";\n/, "")
    .replaceAll(
      'require("ajv/dist/runtime/ucs2length").default',
      "function ucs2length(str) { let n = 0; for (const _ of str) n++; return n; }",
    );
  if (/\brequire\s*\(|^\s*import\b|^\s*export\b[^;\n]*\bfrom\b/m.test(code)) {
    throw new Error("the standalone validators import a module");
  }
  let typed = 0;
  code = code.replace(/^export const (\w+) = (\w+);$/gm, (line, name, fn) => {
    if (!exported.has(name)) throw new Error(`unexpected export ${name}`);
    typed += 1;
    return `export const ${name}: Validator<${exported.get(name).type}> = ${fn};`;
  });
  if (typed !== exported.size) throw new Error("unexpected standalone output");
  const names = [...exported.values()].map(({ type }) => type).join(", ");
  return (
    "// @ts-nocheck: Ajv's output, typed through its exports.\n" +
    HEADER +
    `import type { ${names} } from "./messages.js";\n` +
    'import type { Validator } from "../validator.js";\n\n' +
    code
  );
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });
writeFileSync(`${outDir}messages.ts`, types);
for (const { dir, aggregate, messages } of directions) {
  writeFileSync(
    `${outDir}${dir}-validators.ts`,
    validators(dir, aggregate, messages),
  );
}
